### ISSUE TITLE
Completly broken when trying to switch to a bot account.

### ISSUE THREAD

**Issue by Ayfri** [powercord-community/multitask#9]
Discord can't login in when you have switched to a bot account, so uninstall and reinstall is required. 👀

**Comment by Ayfri** [comment]
Uninstall and reinstall doesn't work, I can't do anything, it don't load, can someone help me ?

**Comment by cyyynthia** [comment]
Using bot tokens is not supported and never will. Use Ctrl+Shift+I, go to Application, Local Storage, `https://canary.discordapp.com`, and clear the token key.

**Comment by YoJames2019** [comment]
> Using bot tokens is not supported and never will. Use Ctrl+Shift+I, go to Application, Local Storage, `https://canary.discordapp.com`, and clear the token key.

that unfortunately doesnt work

**Comment by YoJames2019** [comment]
when i refresh it just replaces it again

**Comment by YoJames2019** [comment]
you actually have to delete it, close discord completely and then reopen

**Comment by Ayfri** [comment]
Hi!

There is [that modified Discord Client](https://github.com/Flam3rboy/discord-bot-client) that lets you use bot tokens and use Discord by being the bot, can't you do something similar?

**Comment by cyyynthia** [comment]
Bot support will not be added.

**Comment by YoJames2019** [comment]
apparently its pulling from a tokenManager? i cant login to discord canary because of this and your earlier advice has no effect

[AuthenticationStore] handleConnectionClosed called with code 4013. {tokenManagerHasToken: true, storageHasToken: false}

**Comment by YoJames2019** [comment]
nvm, just ended up uninstalling discord
